using System.Data;
using System.Reflection;

namespace TOF.Data.Abstractions
{
    public interface IDbModelPropertyStrategy
    {
        PropertyInfo GetPropertyInfo();
        string GetParameterName();
        DbType? GetMapDbType();
        ParameterDirection GetParameterDirection();
        int? GetLength();
        bool IsMaxLength();
        bool IsKey();
        bool IsAllowNull();
        bool IsIncremental();
        bool IsAutoGenerated();
        bool IsAutoGeneratedAtUpdate();
        bool IsIgnoreProperty();
        DbIgnorePropertyKinds GetIgnorePropertyKinds();
        IDbModelPropertyStrategy DbName(string name);
        IDbModelPropertyStrategy AsKey();
        IDbModelPropertyStrategy MapDbType(DbType type);
        IDbModelPropertyStrategy AllowNull();
        IDbModelPropertyStrategy AsIncremental();
        IDbModelPropertyStrategy AsAutoGenerated();
        IDbModelPropertyStrategy AsAutoGeneratedAtUpdate();
        IDbModelPropertyStrategy Length(int length);
        IDbModelPropertyStrategy AsMaxLength();
        IDbModelPropertyStrategy IgnoreProperty(DbIgnorePropertyKinds ignorePropertyKinds);
        IDbModelPropertyStrategy AsOutputParameter();
        IDbModelPropertyStrategy AsReturnParameter();
        IDbModelPropertyStrategy AsInputOutputParameter();
    }
}