using System;

namespace tofx.Data.Annotations
{
    /// <summary>
    /// Mark the property as auto-incremental column in database.
    /// FOR GUID and DATETIME USAGE ONLY.
    /// </summary>
    [AttributeUsage(AttributeTargets.Property, Inherited = false, AllowMultiple = false)]
    public class AutoGeneratedAttribute : Attribute
    {
        public bool AtUpdate { get; set; }
        public bool AtInsert { get; set; }

        public AutoGeneratedAttribute()
        {
            AtInsert = true;
            AtUpdate = false;
        }
    }
}
